language: python
env:
- TOX_ENV=py26
- TOX_ENV=py27
- TOX_ENV=py33
- TOX_ENV=py34
- TOX_ENV=pypy
- TOX_ENV=docs
- TOX_ENV=coverage

install:
    - pip install --use-mirrors tox coveralls
script: tox -e $TOX_ENV
after_success: coveralls
